# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.11.1
lapack_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print (Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
print (Z)
print (Z.size)
print ("%d"%Z.size*Z.itemsize)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
100
100100100100100100100100


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [24]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `u'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
Z = np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [35]:
print (Z)
Z = Z[::-1]
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [39]:
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [52]:
Z = [1,2,0,0,4,0]
for idx, val in enumerate(Z):
    if val is 0:
        print(idx)
print (np.nonzero(Z))
    

2
3
5
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
print (np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [63]:
print (np.random.random([3,3,3]))

[[[ 0.00952856  0.64927631  0.52648855]
  [ 0.6465133   0.64776606  0.88029109]
  [ 0.97931389  0.06655212  0.59084091]]

 [[ 0.61186855  0.08772243  0.54704332]
  [ 0.30876316  0.85455021  0.02145784]
  [ 0.58538642  0.20506756  0.9579267 ]]

 [[ 0.56932891  0.56427084  0.61010618]
  [ 0.33391156  0.37007156  0.29215357]
  [ 0.77169822  0.39573719  0.60271155]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [66]:
Z = np.random.random((10,10))
print Z.min()
print Z.max()

0.0266972684535
0.99006475899


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [67]:
Z = np.random.random(30)
print Z.mean()

0.492358481098


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [84]:
n=10
Z = np.zeros((n,n))
%for i in np.arange(1,n-1):
%    for j in np.arange(1,n-1):
%                Z[i,j] = 1
Z[1:-1,1:-1] = 1
print (Z)


ERROR:root:Line magic function `%for` not found.
ERROR:root:Line magic function `%for` not found.
ERROR:root:Line magic function `%Z` not found.


[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [93]:
Z = np.random.random((4,4))
A = np.zeros((7,7))
A[1:-2,1:-2] = Z
print (Z)
print (np.pad(Z,pad_width=1,mode='constant', constant_values=0))

[[ 0.61742173  0.18640047  0.49551409  0.62733297]
 [ 0.49212738  0.57431868  0.07390702  0.98118884]
 [ 0.34066634  0.53449902  0.85730697  0.05242821]
 [ 0.07531654  0.62257707  0.59197055  0.44010938]]
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.61742173  0.18640047  0.49551409  0.62733297  0.        ]
 [ 0.          0.49212738  0.57431868  0.07390702  0.98118884  0.        ]
 [ 0.          0.34066634  0.53449902  0.85730697  0.05242821  0.        ]
 [ 0.          0.07531654  0.62257707  0.59197055  0.44010938  0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [103]:
print (0 * np.nan)
print (np.nan==np.nan)
print (np.inf > np.nan)
print (np.nan - 3)
print (0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [110]:

Z = np.diag(np.arange(1,5), k= 1)
print Z

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [122]:
Z = np.zeros((8,8))
Z[1::2,1::2] = 1
Z[0::2,0::2] = 1
Z

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [123]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [125]:
np.tile(np.array([[1,0],[0,1]]), (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [145]:
Z = np.random.random((5,5))
print Z
print
Z1 = (Z - Z.mean())/ Z.std()
print Z1
print
Z2 = (Z - Z.min())/ (Z.max() - Z.min())
print Z2
print



[[ 0.42238848  0.19987956  0.07949457  0.72133678  0.69529628]
 [ 0.55341867  0.82859448  0.340239    0.12924482  0.84025584]
 [ 0.44037944  0.93461214  0.73247017  0.6606731   0.18470848]
 [ 0.69182991  0.57287469  0.11798303  0.63629163  0.23728853]
 [ 0.84362105  0.96125974  0.90113391  0.15698063  0.73045611]]

[[-0.43068645 -1.21541955 -1.63998716  0.62362914  0.53179084]
 [ 0.03142414  1.00190013 -0.72040703 -1.46453053  1.04302683]
 [-0.36723686  1.37579782  0.66289383  0.40968358 -1.26892413]
 [ 0.51956582  0.10004065 -1.50424803  0.32369626 -1.08348749]
 [ 1.05489508  1.46977718  1.2577285  -1.36671331  0.65579074]]

[[ 0.38887214  0.13652726  0.          0.72790606  0.69837382]
 [ 0.53747201  0.84954582  0.29570734  0.0564212   0.86277084]
 [ 0.40927548  0.96977927  0.74053232  0.65910806  0.11932191]
 [ 0.69444265  0.55953687  0.04364933  0.63145731  0.17895236]
 [ 0.86658729  1.          0.93181198  0.08787606  0.73824819]]



#### 23. Create a custom dtype that describes a color as four unisgned bytes (RGBA) (★☆☆)

In [148]:
np.dtype([("r", np.ubyte, 1),
          ("g", np.ubyte, 1),
          ("b", np.ubyte, 1),
          ("c", np.ubyte, 1)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('c', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [152]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print A
print B
print

np.dot(A,B)

[[ 0.2067815   0.41252103  0.62430147]
 [ 0.00706333  0.84052824  0.84140924]
 [ 0.68043026  0.94382251  0.54588207]
 [ 0.45273779  0.23699285  0.39000589]
 [ 0.53578278  0.37550604  0.11779707]]
[[ 0.92278437  0.0208784 ]
 [ 0.47288153  0.63898123]
 [ 0.37402757  0.20514641]]



array([[ 0.61939427,  0.39598367],
       [ 0.71869846,  0.70984133],
       [ 1.27838159,  0.72927692],
       [ 0.67572186,  0.24089473],
       [ 0.7160412 ,  0.27529324]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [157]:
Z = np.arange(14)
Z[3:8] *= -1
print Z

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10 11 12 13]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [164]:
print range(5)
print(sum(range(5),-1))
from numpy import sum
print(sum(range(5),0))

[0, 1, 2, 3, 4]
10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [189]:
Z =np.array([1,3,4])
print Z ** Z
print 2<< Z >>2
print Z <- Z
print 1j*Z
print Z/1/1
print Z<Z>Z


[  1  27 256]
[1 4 8]
[False False False]
[ 0.+1.j  0.+3.j  0.+4.j]
[1 3 4]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:

print np.array([1.1,5.1]).astype(int).astype(float)

[ 1.  5.]


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
z = np.random.uniform(-10,10,20)
print z

print (abs(z).astype(int)+1)*((z>0) * 2 - 1)

[ 1.35852473 -4.57395461  2.47914762 -7.17198135 -0.59923408  8.9681701
  5.4961121  -6.87221946 -6.67314136  4.8805544   1.85469946 -7.09506537
  0.0913638   3.84204083  6.8238199   4.13369906 -3.24439856  8.48747238
 -6.32236155 -0.27877234]
[ 2 -5  3 -8 -1  9  6 -7 -7  5  2 -8  1  4  7  5 -4  9 -7 -1]


#### 30. How to find common values between two arrays? (★☆☆)

In [35]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print z1
print z2
np.intersect1d(z1,z2)

[3 8 5 1 1 8 8 9 0 6]
[3 7 6 0 5 4 9 7 5 0]


array([0, 3, 5, 6, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [45]:
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
print Z

[ inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
np.emath.sqrt(-1) == np.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [52]:
yesterday= np.datetime64('today', 'D')- np.timedelta64(1,'D')
print yesterday

2016-11-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [58]:
np.arange('2016-07','2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A anb B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in an array? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to I sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)